### ISSUE TITLE
Map and directions printing version is not usable

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#620]
### Expected Behaviour

I should be able to print a version of the map, along with the directions. This version should be usable.

### Actual Behaviour

The printing version is not usable, especially the directions.

**Comment by aaboffill** [comment]
I'll try to make my first contribution to sous-chef with this issue.

**Comment by lingxiaoyang** [comment]
Here are some changes I have made, to let it print better in Chrome.

But for Firefox there's still a important problem that it only prints one page and truncates at the client list or the route instructions. I cannot figure it out.

Perhaps it is necessary to create a print view for this purpose, but it is not very easy to reproduce dynamic content in the new window, preserving what the user has interacted with the leaflet map.

Another more creative way of doing this is to perform a JavaScript capture of the map as a canvas element and put the active route information in the new window (`new_window.document.write()`), but this may be too experimental: https://github.com/niklasvh/html2canvas

In short, I haven't come up with a good solution for this issue.

````html
diff --git a/src/delivery/templates/organize_route.html b/src/delivery/templates/organize_route.html
index d970dcd..5910898 100644
--- a/src/delivery/templates/organize_route.html
+++ b/src/delivery/templates/organize_route.html
@@ -37,15 +37,15 @@
         data-can-save="{{ can_edit_data|yesno:"yes,no" }}">
     {% leaflet_map "main" callback="main_map_init" %}
   </div>
-  <div class="three wide column">
+  <div class="three wide column" id="sc-routing">
     <div class="controls"></div>
   </div>
 </div>
 
-<a href="{% url 'delivery:route_sheet_id' id=route.id %}" class="ui big labeled icon button" title="{% trans 'Print the route sheet' %}">
+<a href="{% url 'delivery:route_sheet_id' id=route.id %}" class="ui big labeled icon button no-print" title="{% trans 'Print the route sheet' %}">
   <i class="list layout icon"></i>{% trans 'Route sheet' %}
 </a>
-<a href="{% url 'delivery:routes' %}" class="ui big labeled {% if orders == 0 %} disabled {% endif %} icon button" title="{% trans 'View routes list' %}">
+<a href="{% url 'delivery:routes' %}" class="ui big labeled {% if orders == 0 %} disabled {% endif %} icon button no-print" title="{% trans 'View routes list' %}">
   <i class="chevron left icon"></i>{% trans 'View routes' %}
 </a>
````

````css
diff --git a/src/frontend/scss/admin/admin.scss b/src/frontend/scss/admin/admin.scss
index 564ac61..c437bcb 100644
--- a/src/frontend/scss/admin/admin.scss
+++ b/src/frontend/scss/admin/admin.scss
@@ -282,6 +282,17 @@ ul.doughnut-legend {
 .leaflet-routing-alt {
   max-height:400px;
 }
+@media only print {
+  /* Show the map as much as possible */
+  #route_map {width:100%!important}
+  /* Force routing to next row */
+  #sc-routing {width:100%!important}
+  /* Occupy full width */
+  #sc-routing .leaflet-routing-container {width:100%!important}
+  /* Show all routes when printing */
+  .leaflet-routing-alt {max-height:none!important}
+}
+
 
 /* Avatars */
 .list-avatars {
diff --git a/src/frontend/scss/base/print.scss b/src/frontend/scss/base/print.scss
index b08e459..a1d4a39 100644
--- a/src/frontend/scss/base/print.scss
+++ b/src/frontend/scss/base/print.scss
@@ -1,4 +1,6 @@
 @media only print {
+    body, html {height:none!important}
+
     .ui.left.fixed.vertical.inverted.menu
     {display:none;}
 
@@ -17,6 +19,5 @@
     div{font-size:xx-small;}
 
     .no-print {
-        display:none;}
+        display:none!important;}
 }
````
